version: 2

updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - pawellabaj
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: wekly
    reviewers:
      - pawellabaj
    labels:
      - dependencies