version: 2

updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - pawellabaj
    labels:
      - dependencies
    commit-message:
      prefix: "maven: "
      include: "scope"
      
  - package-ecosystem: github-actions
    directory: ".github/workflows"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - pawellabaj
    labels:
      - build
    commit-message:
      prefix: "action: "
      include: "scope"
