branchName: 'issue-${issue.number}-${issue.title[0,64],}'
gitSafeReplacementChar: '-'
autoCloseIssue: true

openDraftPR: true
prSkipCI: true

conventionalPrTitles: true

branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: fix/
  - label: question
    skip: true

conventionalLabels:
  chore:
    build: ':construction_worker:'

copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true