branchName: 'issue-${issue.number}-${issue.title[0,64],}'
gitSafeReplacementChar: '-'
autoCloseIssue: true

branches:
  - label: enhancement
    prefix: feature/
  - label: documentation
    prefix: doc/
  - label: bug
    prefix: fix/
  - label: build
    prefix: build/
  - label: question
    skip: true

openDraftPR: true
prSkipCI: true

conventionalPrTitles: true

conventionalLabels:
  docs:
    documentation: ':memo:'
  fix:
    bug: ':ambulance:'
    performance: ':zap:'
    security: ':lock:'
    build: ':construction_worker:'
  feature:
    enhancement: ':sparkles:'
    dependencies: ':arrow_up:'
  breaking:
    breaking-change: ':boom:'
    breaking change: ':boom:'

copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true