changelog:
  exclude:
    labels:
      - ignore-for-release-notes
      - question
  categories:
    - title: "Breaking Changes :boom:"
      labels:
        - breaking-change
        - breaking change
    - title: "New features :sparkles:"
      labels:
        - enhancement
        - feat
        - feature
    - title: "Documentation update :memo:"
      labels:
        - doc
        - documentation
    - title: "Bug fixes :bug:"
      labels:
        - bug
        - fix
    - title: "Dependencies :arrow_up:"
      labels:
        - dependencies
    - title: "Housekeeping :wrench:"
      labels:
        - build
        - "*"