branches: [main]
tagFormat: v${version}
debug: false
plugins:
  - "semantic-release-export-data"
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - type: build
          scope: dep
          release: patch
