name: Build and verify

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build-and-verify:
    name: Build and verify
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Compile the code
        shell: bash
        run: mvn clean compile test-compile

      - name: Install locally
        shell: bash
        run: mvn -B install -U --fail-never -DskipTests=true

      - name: Cache SonarCloud packages
        uses: actions/cache@v3.3.1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Verify and trigger Sonar analysis
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -U --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true

      - name: Sonar Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: target/sonar/report-task.txt

      - name: Build a test report
        uses: ScaCap/action-surefire-report@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_if_no_tests: false
          fail_on_test_failures: true
