name: CI

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request_review:
    types:
      - submitted

jobs:
  build_:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Compile the code
        shell: bash
        run: mvn clean compile test-compile

      - name: Install locally
        if: ${{ !env.runSonar }}
        shell: bash
        run: mvn -B install -U --fail-never -DskipTests=true

      - name: Verify code
        if: ${{ !env.runSonar }}
        shell: bash
        run: mvn -B verify -U --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true

      - name: Build a test report
        uses: ScaCap/action-surefire-report@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_if_no_tests: false
          fail_on_test_failures: true
