name: Deploy

permissions:
  contents: write

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Install GPG secret key
        id: install-secret-key
        shell: bash
        run: cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import

      - name: Build packages
        shell: bash
        run: mvn -B package javadoc:javadoc -U --fail-never -DskipTests=true

      - name: Install locally
        shell: bash
        run: mvn -B install -U --fail-never -DskipTests=true

      - name: Publish package
        shell: bash
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
