name: Deploy

permissions:
  contents: write

on:
  release:
    types: [published]

concurrency:
  group: deploy-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Install GPG secret key
        id: install-secret-key
        shell: bash
        run: cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import



#      - name: Install locally
#          shell: bash
#          run: mvn -B -U install -DskipTests=true -Dsource.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
#
#            - name: Configure Git user
#              run: |
#                git config user.email "actions@github.com"
#                git config user.name "GitHub Actions"
#
#            - name: Maven release:prepare
#              shell: bash
#              env:
#                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#              run: mvn -B -Darguments="-Dmaven.test.skip -DskipTests -Dsource.skip=true -Dmaven.javadoc.skip=true -Dmaven.deploy.skip=true -Dgpg.skip=true" release:prepare -DreleaseVersion=$NEXT_VERSION
#
#
#
#      - name: Publish package
#        shell: bash
#        run: mvn -B -U deploy org.sonatype.plugins:nexus-staging-maven-plugin:deploy-staged -DskipTests=true
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
