name: Deploy

permissions:
  contents: write

on:
  release:
    types: [published]

concurrency:
  group: deploy-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Prepare Release
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.ref }}
    steps:
      - name: Release version
        shell: bash
        run: |
          echo Release version is: $RELEASE_VERSION

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Install GPG secret key
        id: install-secret-key
        shell: bash
        run: cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import

      - name: Create release branch
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -b release-${{ env.RELEASE_VERSION }} origin/main
          git push --set-upstream origin release-${{ genv.RELEASE_VERSION }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          mvn release:prepare -DreleaseVersion=${{ env.RELEASE_VERSION }} -B -P release
          mvn release:perform -DreleaseVersion=${{ env.RELEASE_VERSION }} -B -P release

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release-${{ env.RELEASE_VERSION }}
          title: "Release version ${{ env.RELEASE_VERSION }}"
          body: "This pull request contains the changes required for the ${{ env.RELEASE_VERSION }} release."
          assignees: pawellabaj
          reviewers: pawellabaj
          delete-branch: true
