name: Create draft release

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Verify]
    types:
      - completed
    branches:
      - main

concurrency:
  group: draft-release-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  get-next-version:
    name: Get Next version
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    if: needs.get-next-version.outputs.new-release-published == 'true'
    needs:
      - get-next-version
    env:
      NEXT_VERSION: ${{ needs.get-next-version.outputs.new-release-version }}
    steps:
      - name: Next version
        shell: bash
        run: |
          echo Next version is: $NEXT_VERSION

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Create Github draft release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ env.NEXT_VERSION }}




