name: prepare Release draft

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '*'

concurrency:
  group: ${{ github.workflow }}

jobs:
  get-next-version:
    name: Get Next version
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4

  release-prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    if: needs.get-next-version.outputs.new-release-published == 'true'
    needs:
      - get-next-version
    env:
      NEXT_VERSION: ${{ needs.get-next-version.outputs.new-release-version }}
    steps:
      - name: Next version
        shell: bash
        run: |
          echo "::notice Next version: $NEXT_VERSION"

      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Maven release:prepare
        shell: bash
        run: mvn -B -Darguments="-Dmaven.test.skip -DskipTests" release:prepare -Drelease.version=$NEXT_VERSION -DdryRun





