name: prepare Release draft

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '*'

concurrency:
  group: ${{ github.workflow }}

jobs:
#  get-next-version:
#    uses: semantic-release-action/next-release-version/internal@v4
#    with:
#      branches: |
#        ['main']
#    outputs:
#      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
#      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}

  release-prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Get next version
        uses: semantic-release-action/next-release-version/internal@v4
        with:
          branches: |
            [ main ]
      - name: Next version
        if: steps.get-next-version.outputs.new-release-published == 'true'
        env:
          NEXT_VERSION: ${{ steps.get-next-version.outputs.new-release-version }}
        shell: bash
        run: |
          echo "::notice Next version: $NEXT_VERSION"

