name: prepare Release draft

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '*'

concurrency:
  group: ${{ github.workflow }}

jobs:
  get-next-version:
    name: Get Next version
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4

  release-prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    if: needs.get-next-version.outputs.new-release-published == 'true'
    needs:
      - get-next-version
    env:
      NEXT_VERSION: ${{ needs.get-next-version.outputs.new-release-version }}
    steps:
      - name: Next version
        shell: bash
        run: |
          echo Next version is: $NEXT_VERSION

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Install locally
        shell: bash
        run: mvn -B install -U --fail-never -DskipTests=true

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Maven release:prepare
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B -Darguments="-Dmaven.test.skip -DskipTests" release:prepare -DreleaseVersion=$NEXT_VERSION -DautoVersionSubmodules=true -DdryRun 
          cat release.properties




