name: Release and release - internal

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
        description: Version to be released

jobs:
  print-version:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The version is ${{ inputs.release-version }}
