name: prepare Release draft

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '*'

concurrency:
  group: ${{ github.workflow }}

jobs:
  release-prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up configuration
        shell: bash
        run: |
          echo '{"branches": ["main"]}' > .releaserc
      - name: Get next version
        uses: semantic-release-action/next-release-version/internal@v4
      - name: Next version
        if: steps.get-next-version.outputs.new-release-published == 'true'
        env:
          NEXT_VERSION: ${{ steps.get-next-version.outputs.new-release-version }}
        shell: bash
        run: |
          echo "::notice Next version: $NEXT_VERSION"

